FROM node:0.11.14

MAINTAINER Cai Guanhao (caiguanhao@gmail.com)

RUN apt-get update && apt-get install -y libvips-dev libgsf-1-dev

ADD package.backend.json /excavator/package.json

WORKDIR /excavator

RUN npm --loglevel warn install

RUN npm --loglevel warn install -g gulp

# use global gulp so we won't install it again
RUN npm link gulp

ADD package.json /excavator/package.json

RUN npm --loglevel warn install

ENV NODE_ENV production

CMD gulp build

ADD . /excavator
