db:
  image: mongo:2.6.5
  restart: always
  mem_limit: 200M
  volumes:
    - /data/mongo/excavator:/data/db

backend:
  build: .
  restart: always
  mem_limit: 200M
  dockerfile: Dockerfile.backend
  links:
    - db
  ports:
    - '127.0.0.1:56600:3000'
  volumes:
    - /srv/excavator/admincontent:/admincontent
    - /srv/excavator/usercontent:/usercontent

frontend:
  build: .
  dockerfile: Dockerfile.frontend
  environment:
    - GIT_HEAD_COMMIT
    - GIT_HEAD_DATE
    - GIT_HEAD_AUTHOR
    - GIT_HEAD_FILE_COUNT
  volumes:
    - /srv/excavator/dist:/excavator/dist # also in Makefile
