FROM node:0.10.33

MAINTAINER Cai Guanhao (caiguanhao@gmail.com)

RUN apt-get update && apt-get install -y libvips-dev libgsf-1-dev

ADD package.backend.json /excavator/package.json

WORKDIR /excavator

ENV NODE_ENV production

RUN npm --loglevel warn install

ENV NODE_ENV development

RUN npm --loglevel warn install -g gulp

ADD package.json /excavator/package.json

RUN npm --loglevel warn install

ADD . /excavator

ENV NODE_ENV production

CMD gulp build
